extend type Mutation {
  roles: RoleMutations
}

type RoleMutations {
  create(input: CreateRoleInput): Role
  update(input: UpdateRoleInput): Role
  delete(input: DeleteRoleInput): Role
}

type Role {
  id: String!
  name: String!
}

input CreateRoleInput {
  name: String!
}

input UpdateRoleInput {
  id: String!
  name: String!
}

input DeleteRoleInput {
  id: String!
}
